language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
install:
  - pip install coveralls
  - pip install -e '.[test]'
script: coverage run --source zru setup.py test
after_success: coveralls
cache: pip